# Change these first
owner: LilahSolutions # Your GitHub organization or username, where this repository lives
repo: app-monitor # The name of this repository

sites:      
  - name: Qrio - Api
    url: https://qrio.com.ar/qrio/api/mp/origin/MP/IPN/4617042972482396-060307-01f071f78d668c70b89786162076a657-1132424683?topic=payment&id=1452147278
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{
		"key": "topic",
		"value": "payment"
	},
	{
		"key": "",
		"value": "",
		"disabled": true
	},
	{
		"key": "id",
		"value": "1452147278"
    }'
    assignees:
      - PatricioHeduan
    maxResponseTime: 5000
    
   - name: Qrio - Payments
     url: https://qrio.com.ar/qrio/api/mp/origin/MP/IPN/4617042972482396-060307-01f071f78d668c70b89786162076a657-1132424683?topic=payment&id=1452147278
     method: POST
     headers:
       - "Content-Type: application/json"
     body: '{
		"key": "topic",
		"value": "payment"
	},
	{
		"key": "",
		"value": "",
		"disabled": true
	},
	{
		"key": "id",
		"value": "1452147278"
     }'
     assignees:
       - PatricioHeduan
     maxResponseTime: 5000
    
    
    - name: Qrio - Backoffice
      url: qrio.com.ar/api/qrio-backoffice/client/user/c8e582c7-b4e1-44b9-b484-fd5cec435214
      method: GET
      assignees:
        - PatricioHeduan
      maxResponseTime: 5000

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: lilahsolutions.github.io
  baseUrl: /app-monitor
  logoUrl: https://web.lila.com.ar/landing/images/lila-logo-white.svg
  name: Lila Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
